### ISSUE TITLE
channel Telegram

### ISSUE THREAD

**Issue by geekoff7** [beigirad/IranianDevelopersBlogsAndChannels#1]
https://t.me/geekoff
 بیشتر درمورد نرم افزار ازاد و برنامه نویسی مینویسم

**Comment by beigirad** [comment]
Thanks.
commited in [this](https://github.com/beigirad/IranianDevelopersBlogsAndChannels/commit/6aef47191f20c6a05be8dcb2255acd8700b6cac2)
