### ISSUE TITLE
چند کانال و وبلاگ

### ISSUE THREAD

**Issue by abbasnaqdi** [beigirad/IranianDevelopersBlogsAndChannels#4]
کانال رادیوگیک از جادی میر میرانی عزیز 
https://t.me/jadiradio

کانال خبرگزاری توسعه دهندگان :
https://t.me/irdevnews

کانال سایت سکان آکادمی (مطالب مفید برای برنامه نویس ها)
https://t.me/sokanacademy

وبلاگ عباس نقدی : مطالب مفید و تجربیات یک برنامه نویس موبایل و بکند
http://okcode.ir

کانال آموزش UIUX : 
https://t.me/uxitten

**Comment by eniac1989** [comment]
آکادمی برنامه نویسی
https://t.me/programmingAcademy
