### ISSUE TITLE
سلام 

### ISSUE THREAD

**Issue by younes372** [beigirad/IranianDevelopersBlogsAndChannels#5]
کنال آپارت و یوتیوب  هم بزارید

**Comment by beigirad** [comment]
اگر کانالی مفیدی میشناسید معرفی کنید
تمرکز این ریپو روی معرفی مطالب مفید فارسی هست.

**Comment by islamoid** [comment]
برنامه نویسی اندروید
@ProgAndroid

**Comment by beigirad** [comment]
این کانال غیرفعال شده و به #گپ منتقل شده.
